name = "keycook"
grammar = "keycook"
path_suffixes = ["kc"]
line_comments = ["// "]
word_characters = ["_", ":", "-", "@", "."]
autoclose_before = ")}"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
tab_size = 2
