/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 68
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_ident = 1,
  anon_sym_EQ = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  sym_comment = 5,
  aux_sym_alias_name_token1 = 6,
  sym_alias_value = 7,
  anon_sym_PIPE = 8,
  anon_sym_COLON = 9,
  sym_null = 10,
  sym_action_name = 11,
  sym_args = 12,
  sym_string = 13,
  sym_source_file = 14,
  sym__item = 15,
  sym_body_def = 16,
  sym_body_use = 17,
  sym_alias = 18,
  sym_alias_name = 19,
  sym_block = 20,
  sym_context_header = 21,
  sym_alias_ref = 22,
  sym_prefix_header = 23,
  sym_binding = 24,
  sym_keys = 25,
  sym_key = 26,
  sym_actions = 27,
  sym__action = 28,
  sym_action = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_context_header_repeat1 = 31,
  aux_sym_prefix_header_repeat1 = 32,
  aux_sym_keys_repeat1 = 33,
  aux_sym_actions_repeat1 = 34,
  aux_sym_actions_repeat2 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_comment] = "comment",
  [aux_sym_alias_name_token1] = "alias_name_token1",
  [sym_alias_value] = "alias_value",
  [anon_sym_PIPE] = "|",
  [anon_sym_COLON] = ":",
  [sym_null] = "null",
  [sym_action_name] = "action_name",
  [sym_args] = "args",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_body_def] = "body_def",
  [sym_body_use] = "body_use",
  [sym_alias] = "alias",
  [sym_alias_name] = "alias_name",
  [sym_block] = "block",
  [sym_context_header] = "context_header",
  [sym_alias_ref] = "alias_ref",
  [sym_prefix_header] = "prefix_header",
  [sym_binding] = "binding",
  [sym_keys] = "keys",
  [sym_key] = "key",
  [sym_actions] = "actions",
  [sym__action] = "_action",
  [sym_action] = "action",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_context_header_repeat1] = "context_header_repeat1",
  [aux_sym_prefix_header_repeat1] = "prefix_header_repeat1",
  [aux_sym_keys_repeat1] = "keys_repeat1",
  [aux_sym_actions_repeat1] = "actions_repeat1",
  [aux_sym_actions_repeat2] = "actions_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_comment] = sym_comment,
  [aux_sym_alias_name_token1] = aux_sym_alias_name_token1,
  [sym_alias_value] = sym_alias_value,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_null] = sym_null,
  [sym_action_name] = sym_action_name,
  [sym_args] = sym_args,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_body_def] = sym_body_def,
  [sym_body_use] = sym_body_use,
  [sym_alias] = sym_alias,
  [sym_alias_name] = sym_alias_name,
  [sym_block] = sym_block,
  [sym_context_header] = sym_context_header,
  [sym_alias_ref] = sym_alias_ref,
  [sym_prefix_header] = sym_prefix_header,
  [sym_binding] = sym_binding,
  [sym_keys] = sym_keys,
  [sym_key] = sym_key,
  [sym_actions] = sym_actions,
  [sym__action] = sym__action,
  [sym_action] = sym_action,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_context_header_repeat1] = aux_sym_context_header_repeat1,
  [aux_sym_prefix_header_repeat1] = aux_sym_prefix_header_repeat1,
  [aux_sym_keys_repeat1] = aux_sym_keys_repeat1,
  [aux_sym_actions_repeat1] = aux_sym_actions_repeat1,
  [aux_sym_actions_repeat2] = aux_sym_actions_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_alias_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_alias_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_action_name] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_body_def] = {
    .visible = true,
    .named = true,
  },
  [sym_body_use] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_name] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_context_header] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_header] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_keys] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_actions] = {
    .visible = true,
    .named = true,
  },
  [sym__action] = {
    .visible = false,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_context_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_prefix_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_keys_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_actions_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_actions_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_actions = 1,
  field_args = 2,
  field_header = 3,
  field_keys = 4,
  field_name = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_actions] = "actions",
  [field_args] = "args",
  [field_header] = "header",
  [field_keys] = "keys",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 2},
  [2] =
    {field_header, 0},
  [3] =
    {field_name, 0},
  [4] =
    {field_actions, 2},
    {field_keys, 0},
  [6] =
    {field_args, 1},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 2,
  [9] = 4,
  [10] = 5,
  [11] = 6,
  [12] = 7,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 16,
  [17] = 15,
  [18] = 16,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 22,
  [27] = 25,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 28,
  [34] = 34,
  [35] = 31,
  [36] = 36,
  [37] = 32,
  [38] = 30,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 40,
  [43] = 43,
  [44] = 44,
  [45] = 39,
  [46] = 46,
  [47] = 41,
  [48] = 46,
  [49] = 49,
  [50] = 50,
  [51] = 43,
  [52] = 49,
  [53] = 44,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 58,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 63,
  [66] = 64,
  [67] = 60,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '"', 2,
        '(', 35,
        '/', 37,
        ':', 34,
        '=', 23,
        '@', 13,
        'n', 40,
        '{', 24,
        '|', 33,
        '}', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '{') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ')') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == 'n') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'l') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'l') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'u') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(14);
      END_STATE();
    case 13:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 14:
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 17:
      if (eof) ADVANCE(21);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '@') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(40);
      if (lookahead == '|') ADVANCE(33);
      if (lookahead == '}') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != ':' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(42);
      END_STATE();
    case 18:
      if (eof) ADVANCE(21);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == '@') ADVANCE(13);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '|') ADVANCE(33);
      if (lookahead == '}') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 19:
      if (eof) ADVANCE(21);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '=') ADVANCE(23);
      if (lookahead == '@') ADVANCE(13);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '|') ADVANCE(33);
      if (lookahead == '}') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(42);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '@') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(40);
      if (lookahead == '|') ADVANCE(33);
      if (lookahead == '}') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != ':' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(42);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ':' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(42);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ':' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_alias_name_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_alias_value);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_alias_value);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_alias_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(36);
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ':' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == ')') ADVANCE(35);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ':' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ':' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'l') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'l') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'u') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ':' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_null);
      if (lookahead == ':') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_null);
      if (lookahead == ':') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_action_name);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_args);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 18},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 18},
  [8] = {.lex_state = 18},
  [9] = {.lex_state = 18},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 18},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 20},
  [14] = {.lex_state = 20},
  [15] = {.lex_state = 20},
  [16] = {.lex_state = 20},
  [17] = {.lex_state = 20},
  [18] = {.lex_state = 20},
  [19] = {.lex_state = 17},
  [20] = {.lex_state = 17},
  [21] = {.lex_state = 18},
  [22] = {.lex_state = 19},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 18},
  [25] = {.lex_state = 20},
  [26] = {.lex_state = 19},
  [27] = {.lex_state = 20},
  [28] = {.lex_state = 18},
  [29] = {.lex_state = 18},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 18},
  [32] = {.lex_state = 18},
  [33] = {.lex_state = 18},
  [34] = {.lex_state = 18},
  [35] = {.lex_state = 18},
  [36] = {.lex_state = 18},
  [37] = {.lex_state = 18},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 18},
  [40] = {.lex_state = 18},
  [41] = {.lex_state = 18},
  [42] = {.lex_state = 18},
  [43] = {.lex_state = 18},
  [44] = {.lex_state = 18},
  [45] = {.lex_state = 18},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 18},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 18},
  [50] = {.lex_state = 18},
  [51] = {.lex_state = 18},
  [52] = {.lex_state = 18},
  [53] = {.lex_state = 18},
  [54] = {.lex_state = 18},
  [55] = {.lex_state = 18},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 7},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 7},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_action_name] = ACTIONS(1),
    [sym_args] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(62),
    [sym__item] = STATE(3),
    [sym_body_def] = STATE(3),
    [sym_body_use] = STATE(3),
    [sym_alias] = STATE(3),
    [sym_alias_name] = STATE(63),
    [sym_block] = STATE(3),
    [sym_context_header] = STATE(64),
    [sym_alias_ref] = STATE(28),
    [sym_prefix_header] = STATE(64),
    [sym_binding] = STATE(3),
    [sym_keys] = STATE(60),
    [sym_key] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_context_header_repeat1] = STATE(21),
    [aux_sym_prefix_header_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__item] = STATE(11),
    [sym_body_def] = STATE(11),
    [sym_body_use] = STATE(11),
    [sym_alias] = STATE(11),
    [sym_alias_name] = STATE(65),
    [sym_block] = STATE(11),
    [sym_context_header] = STATE(66),
    [sym_alias_ref] = STATE(33),
    [sym_prefix_header] = STATE(66),
    [sym_binding] = STATE(11),
    [sym_keys] = STATE(67),
    [sym_key] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_context_header_repeat1] = STATE(21),
    [aux_sym_prefix_header_repeat1] = STATE(24),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__item] = STATE(6),
    [sym_body_def] = STATE(6),
    [sym_body_use] = STATE(6),
    [sym_alias] = STATE(6),
    [sym_alias_name] = STATE(63),
    [sym_block] = STATE(6),
    [sym_context_header] = STATE(64),
    [sym_alias_ref] = STATE(28),
    [sym_prefix_header] = STATE(64),
    [sym_binding] = STATE(6),
    [sym_keys] = STATE(60),
    [sym_key] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_context_header_repeat1] = STATE(21),
    [aux_sym_prefix_header_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_ident] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(4)] = {
    [sym__item] = STATE(2),
    [sym_body_def] = STATE(2),
    [sym_body_use] = STATE(2),
    [sym_alias] = STATE(2),
    [sym_alias_name] = STATE(65),
    [sym_block] = STATE(2),
    [sym_context_header] = STATE(66),
    [sym_alias_ref] = STATE(33),
    [sym_prefix_header] = STATE(66),
    [sym_binding] = STATE(2),
    [sym_keys] = STATE(67),
    [sym_key] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_context_header_repeat1] = STATE(21),
    [aux_sym_prefix_header_repeat1] = STATE(24),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(5)] = {
    [sym__item] = STATE(7),
    [sym_body_def] = STATE(7),
    [sym_body_use] = STATE(7),
    [sym_alias] = STATE(7),
    [sym_alias_name] = STATE(65),
    [sym_block] = STATE(7),
    [sym_context_header] = STATE(66),
    [sym_alias_ref] = STATE(33),
    [sym_prefix_header] = STATE(66),
    [sym_binding] = STATE(7),
    [sym_keys] = STATE(67),
    [sym_key] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_context_header_repeat1] = STATE(21),
    [aux_sym_prefix_header_repeat1] = STATE(24),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(6)] = {
    [sym__item] = STATE(6),
    [sym_body_def] = STATE(6),
    [sym_body_use] = STATE(6),
    [sym_alias] = STATE(6),
    [sym_alias_name] = STATE(63),
    [sym_block] = STATE(6),
    [sym_context_header] = STATE(64),
    [sym_alias_ref] = STATE(28),
    [sym_prefix_header] = STATE(64),
    [sym_binding] = STATE(6),
    [sym_keys] = STATE(60),
    [sym_key] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_context_header_repeat1] = STATE(21),
    [aux_sym_prefix_header_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_ident] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(30),
    [anon_sym_PIPE] = ACTIONS(33),
    [sym_string] = ACTIONS(36),
  },
  [STATE(7)] = {
    [sym__item] = STATE(11),
    [sym_body_def] = STATE(11),
    [sym_body_use] = STATE(11),
    [sym_alias] = STATE(11),
    [sym_alias_name] = STATE(65),
    [sym_block] = STATE(11),
    [sym_context_header] = STATE(66),
    [sym_alias_ref] = STATE(33),
    [sym_prefix_header] = STATE(66),
    [sym_binding] = STATE(11),
    [sym_keys] = STATE(67),
    [sym_key] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_context_header_repeat1] = STATE(21),
    [aux_sym_prefix_header_repeat1] = STATE(24),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(8)] = {
    [sym__item] = STATE(11),
    [sym_body_def] = STATE(11),
    [sym_body_use] = STATE(11),
    [sym_alias] = STATE(11),
    [sym_alias_name] = STATE(65),
    [sym_block] = STATE(11),
    [sym_context_header] = STATE(66),
    [sym_alias_ref] = STATE(33),
    [sym_prefix_header] = STATE(66),
    [sym_binding] = STATE(11),
    [sym_keys] = STATE(67),
    [sym_key] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_context_header_repeat1] = STATE(21),
    [aux_sym_prefix_header_repeat1] = STATE(24),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(41),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(9)] = {
    [sym__item] = STATE(8),
    [sym_body_def] = STATE(8),
    [sym_body_use] = STATE(8),
    [sym_alias] = STATE(8),
    [sym_alias_name] = STATE(65),
    [sym_block] = STATE(8),
    [sym_context_header] = STATE(66),
    [sym_alias_ref] = STATE(33),
    [sym_prefix_header] = STATE(66),
    [sym_binding] = STATE(8),
    [sym_keys] = STATE(67),
    [sym_key] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_context_header_repeat1] = STATE(21),
    [aux_sym_prefix_header_repeat1] = STATE(24),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(43),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(10)] = {
    [sym__item] = STATE(12),
    [sym_body_def] = STATE(12),
    [sym_body_use] = STATE(12),
    [sym_alias] = STATE(12),
    [sym_alias_name] = STATE(65),
    [sym_block] = STATE(12),
    [sym_context_header] = STATE(66),
    [sym_alias_ref] = STATE(33),
    [sym_prefix_header] = STATE(66),
    [sym_binding] = STATE(12),
    [sym_keys] = STATE(67),
    [sym_key] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_context_header_repeat1] = STATE(21),
    [aux_sym_prefix_header_repeat1] = STATE(24),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(45),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(11)] = {
    [sym__item] = STATE(11),
    [sym_body_def] = STATE(11),
    [sym_body_use] = STATE(11),
    [sym_alias] = STATE(11),
    [sym_alias_name] = STATE(65),
    [sym_block] = STATE(11),
    [sym_context_header] = STATE(66),
    [sym_alias_ref] = STATE(33),
    [sym_prefix_header] = STATE(66),
    [sym_binding] = STATE(11),
    [sym_keys] = STATE(67),
    [sym_key] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_context_header_repeat1] = STATE(21),
    [aux_sym_prefix_header_repeat1] = STATE(24),
    [sym_ident] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(47),
    [anon_sym_PIPE] = ACTIONS(33),
    [sym_string] = ACTIONS(36),
  },
  [STATE(12)] = {
    [sym__item] = STATE(11),
    [sym_body_def] = STATE(11),
    [sym_body_use] = STATE(11),
    [sym_alias] = STATE(11),
    [sym_alias_name] = STATE(65),
    [sym_block] = STATE(11),
    [sym_context_header] = STATE(66),
    [sym_alias_ref] = STATE(33),
    [sym_prefix_header] = STATE(66),
    [sym_binding] = STATE(11),
    [sym_keys] = STATE(67),
    [sym_key] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_context_header_repeat1] = STATE(21),
    [aux_sym_prefix_header_repeat1] = STATE(24),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(50),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      sym_ident,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(59), 1,
      sym_null,
    ACTIONS(61), 1,
      sym_action_name,
    STATE(31), 1,
      aux_sym_actions_repeat2,
    ACTIONS(52), 3,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      sym_string,
    STATE(16), 3,
      sym__action,
      sym_action,
      aux_sym_actions_repeat1,
  [29] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_PIPE,
    ACTIONS(66), 1,
      sym_null,
    ACTIONS(68), 1,
      sym_action_name,
    STATE(35), 1,
      aux_sym_actions_repeat2,
    ACTIONS(52), 3,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      sym_string,
    STATE(18), 3,
      sym__action,
      sym_action,
      aux_sym_actions_repeat1,
  [58] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_null,
    ACTIONS(61), 1,
      sym_action_name,
    ACTIONS(72), 1,
      sym_ident,
    STATE(16), 3,
      sym__action,
      sym_action,
      aux_sym_actions_repeat1,
    ACTIONS(70), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [82] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      sym_ident,
    ACTIONS(78), 1,
      sym_null,
    ACTIONS(81), 1,
      sym_action_name,
    STATE(16), 3,
      sym__action,
      sym_action,
      aux_sym_actions_repeat1,
    ACTIONS(74), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [106] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_null,
    ACTIONS(68), 1,
      sym_action_name,
    ACTIONS(72), 1,
      sym_ident,
    STATE(18), 3,
      sym__action,
      sym_action,
      aux_sym_actions_repeat1,
    ACTIONS(70), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [130] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      sym_ident,
    ACTIONS(84), 1,
      sym_null,
    ACTIONS(87), 1,
      sym_action_name,
    STATE(18), 3,
      sym__action,
      sym_action,
      aux_sym_actions_repeat1,
    ACTIONS(74), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [154] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      sym_args,
    ACTIONS(92), 2,
      sym_ident,
      sym_null,
    ACTIONS(90), 5,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_action_name,
      sym_string,
  [172] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      sym_args,
    ACTIONS(92), 2,
      sym_ident,
      sym_null,
    ACTIONS(90), 5,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_action_name,
      sym_string,
  [190] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      sym_ident,
    ACTIONS(100), 1,
      anon_sym_LBRACE,
    ACTIONS(102), 1,
      aux_sym_alias_name_token1,
    ACTIONS(104), 2,
      anon_sym_PIPE,
      sym_string,
    STATE(23), 2,
      sym_alias_ref,
      aux_sym_context_header_repeat1,
  [211] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      sym_ident,
    ACTIONS(110), 1,
      anon_sym_EQ,
    ACTIONS(106), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [228] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_ident,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      aux_sym_alias_name_token1,
    ACTIONS(120), 2,
      anon_sym_PIPE,
      sym_string,
    STATE(23), 2,
      sym_alias_ref,
      aux_sym_context_header_repeat1,
  [249] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_ident,
    ACTIONS(125), 1,
      anon_sym_PIPE,
    ACTIONS(127), 1,
      anon_sym_COLON,
    ACTIONS(130), 1,
      sym_string,
    STATE(56), 1,
      aux_sym_keys_repeat1,
    STATE(34), 2,
      sym_key,
      aux_sym_prefix_header_repeat1,
  [272] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      sym_ident,
      sym_null,
    ACTIONS(134), 5,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_action_name,
      sym_string,
  [287] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      sym_ident,
    ACTIONS(110), 1,
      anon_sym_EQ,
    ACTIONS(106), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [304] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      sym_ident,
      sym_null,
    ACTIONS(134), 5,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_action_name,
      sym_string,
  [319] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    ACTIONS(138), 1,
      sym_ident,
    ACTIONS(141), 1,
      anon_sym_LBRACE,
    ACTIONS(143), 3,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [337] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_ident,
    ACTIONS(130), 1,
      sym_string,
    ACTIONS(146), 2,
      anon_sym_PIPE,
      anon_sym_COLON,
    STATE(34), 2,
      sym_key,
      aux_sym_prefix_header_repeat1,
  [355] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym_action_name,
    ACTIONS(148), 1,
      sym_null,
    STATE(53), 1,
      sym_actions,
    STATE(13), 3,
      sym__action,
      sym_action,
      aux_sym_actions_repeat1,
  [373] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym_ident,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    STATE(32), 1,
      aux_sym_actions_repeat2,
    ACTIONS(150), 3,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      sym_string,
  [391] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym_ident,
    ACTIONS(157), 1,
      anon_sym_PIPE,
    STATE(32), 1,
      aux_sym_actions_repeat2,
    ACTIONS(70), 3,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      sym_string,
  [409] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    ACTIONS(138), 1,
      sym_ident,
    ACTIONS(141), 1,
      anon_sym_LBRACE,
    ACTIONS(143), 3,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [427] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      sym_ident,
    ACTIONS(165), 1,
      sym_string,
    ACTIONS(163), 2,
      anon_sym_PIPE,
      anon_sym_COLON,
    STATE(34), 2,
      sym_key,
      aux_sym_prefix_header_repeat1,
  [445] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym_ident,
    ACTIONS(168), 1,
      anon_sym_PIPE,
    STATE(37), 1,
      aux_sym_actions_repeat2,
    ACTIONS(150), 3,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      sym_string,
  [463] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_ident,
    ACTIONS(177), 1,
      anon_sym_COLON,
    ACTIONS(141), 2,
      anon_sym_LBRACE,
      aux_sym_alias_name_token1,
    ACTIONS(174), 2,
      anon_sym_PIPE,
      sym_string,
  [481] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym_ident,
    ACTIONS(179), 1,
      anon_sym_PIPE,
    STATE(37), 1,
      aux_sym_actions_repeat2,
    ACTIONS(70), 3,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      sym_string,
  [499] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_action_name,
    ACTIONS(182), 1,
      sym_null,
    STATE(44), 1,
      sym_actions,
    STATE(14), 3,
      sym__action,
      sym_action,
      aux_sym_actions_repeat1,
  [517] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_ident,
    ACTIONS(184), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [530] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      sym_ident,
    ACTIONS(190), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [543] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      sym_ident,
    ACTIONS(194), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [556] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      sym_ident,
    ACTIONS(190), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [569] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym_ident,
    ACTIONS(198), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [582] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      sym_ident,
    ACTIONS(202), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [595] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_ident,
    ACTIONS(184), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [608] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_action_name,
    ACTIONS(204), 1,
      sym_null,
    STATE(17), 3,
      sym__action,
      sym_action,
      aux_sym_actions_repeat1,
  [623] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      sym_ident,
    ACTIONS(194), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [636] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym_action_name,
    ACTIONS(206), 1,
      sym_null,
    STATE(15), 3,
      sym__action,
      sym_action,
      aux_sym_actions_repeat1,
  [651] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_ident,
    ACTIONS(210), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [664] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      sym_ident,
    ACTIONS(106), 4,
      anon_sym_LBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [677] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym_ident,
    ACTIONS(198), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [690] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_ident,
    ACTIONS(210), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [703] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      sym_ident,
    ACTIONS(202), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [716] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      sym_ident,
    ACTIONS(177), 3,
      anon_sym_PIPE,
      anon_sym_COLON,
      sym_string,
  [728] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_ident,
    ACTIONS(130), 1,
      sym_string,
    STATE(29), 2,
      sym_key,
      aux_sym_prefix_header_repeat1,
  [742] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_PIPE,
    ACTIONS(214), 1,
      anon_sym_COLON,
    STATE(57), 1,
      aux_sym_keys_repeat1,
  [755] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_COLON,
    ACTIONS(216), 1,
      anon_sym_PIPE,
    STATE(57), 1,
      aux_sym_keys_repeat1,
  [768] = 3,
    ACTIONS(219), 1,
      anon_sym_LBRACE,
    ACTIONS(221), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_alias_value,
  [778] = 3,
    ACTIONS(221), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
    ACTIONS(227), 1,
      sym_alias_value,
  [788] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_COLON,
  [795] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LBRACE,
  [802] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      ts_builtin_sym_end,
  [809] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_EQ,
  [816] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_LBRACE,
  [823] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_EQ,
  [830] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
  [837] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 29,
  [SMALL_STATE(15)] = 58,
  [SMALL_STATE(16)] = 82,
  [SMALL_STATE(17)] = 106,
  [SMALL_STATE(18)] = 130,
  [SMALL_STATE(19)] = 154,
  [SMALL_STATE(20)] = 172,
  [SMALL_STATE(21)] = 190,
  [SMALL_STATE(22)] = 211,
  [SMALL_STATE(23)] = 228,
  [SMALL_STATE(24)] = 249,
  [SMALL_STATE(25)] = 272,
  [SMALL_STATE(26)] = 287,
  [SMALL_STATE(27)] = 304,
  [SMALL_STATE(28)] = 319,
  [SMALL_STATE(29)] = 337,
  [SMALL_STATE(30)] = 355,
  [SMALL_STATE(31)] = 373,
  [SMALL_STATE(32)] = 391,
  [SMALL_STATE(33)] = 409,
  [SMALL_STATE(34)] = 427,
  [SMALL_STATE(35)] = 445,
  [SMALL_STATE(36)] = 463,
  [SMALL_STATE(37)] = 481,
  [SMALL_STATE(38)] = 499,
  [SMALL_STATE(39)] = 517,
  [SMALL_STATE(40)] = 530,
  [SMALL_STATE(41)] = 543,
  [SMALL_STATE(42)] = 556,
  [SMALL_STATE(43)] = 569,
  [SMALL_STATE(44)] = 582,
  [SMALL_STATE(45)] = 595,
  [SMALL_STATE(46)] = 608,
  [SMALL_STATE(47)] = 623,
  [SMALL_STATE(48)] = 636,
  [SMALL_STATE(49)] = 651,
  [SMALL_STATE(50)] = 664,
  [SMALL_STATE(51)] = 677,
  [SMALL_STATE(52)] = 690,
  [SMALL_STATE(53)] = 703,
  [SMALL_STATE(54)] = 716,
  [SMALL_STATE(55)] = 728,
  [SMALL_STATE(56)] = 742,
  [SMALL_STATE(57)] = 755,
  [SMALL_STATE(58)] = 768,
  [SMALL_STATE(59)] = 778,
  [SMALL_STATE(60)] = 788,
  [SMALL_STATE(61)] = 795,
  [SMALL_STATE(62)] = 802,
  [SMALL_STATE(63)] = 809,
  [SMALL_STATE(64)] = 816,
  [SMALL_STATE(65)] = 823,
  [SMALL_STATE(66)] = 830,
  [SMALL_STATE(67)] = 837,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_actions, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_actions, 1, 0, 0),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_actions, 1, 0, 0), SHIFT(48),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_actions, 1, 0, 0), SHIFT(46),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_actions_repeat2, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_actions_repeat2, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_actions_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_actions_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_actions_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_actions_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_actions_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_actions_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 1, 0, 3),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 1, 0, 3),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context_header, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_ref, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_ref, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_name, 1, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_keys, 1, 0, 0), SHIFT(61),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 2, 0, 5),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 2, 0, 5),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_use, 1, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_body_use, 1, 0, 0), REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_body_use, 1, 0, 0), REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_keys_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_actions, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_actions, 2, 0, 0),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_actions, 2, 0, 0), SHIFT(48),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_actions_repeat2, 2, 0, 0), SHIFT_REPEAT(48),
  [160] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prefix_header_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_prefix_header_repeat1, 2, 0, 0),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prefix_header_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_actions, 2, 0, 0), SHIFT(46),
  [171] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_key, 1, 0, 0), REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_key, 1, 0, 0), REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_actions_repeat2, 2, 0, 0), SHIFT_REPEAT(46),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 3, 0, 1),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias, 3, 0, 1),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 2),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 2),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_def, 4, 0, 3),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_def, 4, 0, 3),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 2),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding, 3, 0, 4),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 3, 0, 4),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_def, 5, 0, 3),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_def, 5, 0, 3),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keys, 2, 0, 0),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_keys_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_header, 2, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_keycook(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
    .name = "keycook",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
