/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 54
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_ident = 1,
  anon_sym_EQ = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  sym_comment = 5,
  aux_sym_alias_name_token1 = 6,
  sym_alias_value = 7,
  anon_sym_PIPE = 8,
  anon_sym_COLON = 9,
  sym_null = 10,
  sym_action_name = 11,
  sym_args = 12,
  sym_string = 13,
  sym_source_file = 14,
  sym__item = 15,
  sym_body_def = 16,
  sym_body_use = 17,
  sym_alias = 18,
  sym_alias_name = 19,
  sym_block = 20,
  sym_context_header = 21,
  sym_alias_ref = 22,
  sym_prefix_header = 23,
  sym_binding = 24,
  sym_keys = 25,
  sym_key = 26,
  sym_actions = 27,
  sym__action = 28,
  sym_action = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_context_header_repeat1 = 31,
  aux_sym_prefix_header_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_comment] = "comment",
  [aux_sym_alias_name_token1] = "alias_name_token1",
  [sym_alias_value] = "alias_value",
  [anon_sym_PIPE] = "|",
  [anon_sym_COLON] = ":",
  [sym_null] = "null",
  [sym_action_name] = "action_name",
  [sym_args] = "args",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_body_def] = "body_def",
  [sym_body_use] = "body_use",
  [sym_alias] = "alias",
  [sym_alias_name] = "alias_name",
  [sym_block] = "block",
  [sym_context_header] = "context_header",
  [sym_alias_ref] = "alias_ref",
  [sym_prefix_header] = "prefix_header",
  [sym_binding] = "binding",
  [sym_keys] = "keys",
  [sym_key] = "key",
  [sym_actions] = "actions",
  [sym__action] = "_action",
  [sym_action] = "action",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_context_header_repeat1] = "context_header_repeat1",
  [aux_sym_prefix_header_repeat1] = "prefix_header_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_comment] = sym_comment,
  [aux_sym_alias_name_token1] = aux_sym_alias_name_token1,
  [sym_alias_value] = sym_alias_value,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_null] = sym_null,
  [sym_action_name] = sym_action_name,
  [sym_args] = sym_args,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_body_def] = sym_body_def,
  [sym_body_use] = sym_body_use,
  [sym_alias] = sym_alias,
  [sym_alias_name] = sym_alias_name,
  [sym_block] = sym_block,
  [sym_context_header] = sym_context_header,
  [sym_alias_ref] = sym_alias_ref,
  [sym_prefix_header] = sym_prefix_header,
  [sym_binding] = sym_binding,
  [sym_keys] = sym_keys,
  [sym_key] = sym_key,
  [sym_actions] = sym_actions,
  [sym__action] = sym__action,
  [sym_action] = sym_action,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_context_header_repeat1] = aux_sym_context_header_repeat1,
  [aux_sym_prefix_header_repeat1] = aux_sym_prefix_header_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_alias_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_alias_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_action_name] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_body_def] = {
    .visible = true,
    .named = true,
  },
  [sym_body_use] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_name] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_context_header] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_header] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_keys] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_actions] = {
    .visible = true,
    .named = true,
  },
  [sym__action] = {
    .visible = false,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_context_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_prefix_header_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_actions = 1,
  field_args = 2,
  field_header = 3,
  field_keys = 4,
  field_name = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_actions] = "actions",
  [field_args] = "args",
  [field_header] = "header",
  [field_keys] = "keys",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 2},
  [2] =
    {field_header, 0},
  [3] =
    {field_name, 0},
  [4] =
    {field_actions, 2},
    {field_keys, 0},
  [6] =
    {field_args, 1},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 3,
  [9] = 7,
  [10] = 4,
  [11] = 6,
  [12] = 2,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 18,
  [19] = 18,
  [20] = 20,
  [21] = 17,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 31,
  [33] = 26,
  [34] = 22,
  [35] = 28,
  [36] = 29,
  [37] = 27,
  [38] = 25,
  [39] = 23,
  [40] = 40,
  [41] = 41,
  [42] = 30,
  [43] = 43,
  [44] = 44,
  [45] = 44,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 49,
  [52] = 48,
  [53] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '"', 2,
        '(', 34,
        '/', 36,
        ':', 33,
        '=', 22,
        '@', 13,
        'n', 39,
        '{', 23,
        '|', 32,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == '{') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == 'n') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'l') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'l') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'u') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(14);
      END_STATE();
    case 13:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 17:
      if (eof) ADVANCE(20);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(34);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '@') ADVANCE(13);
      if (lookahead == '|') ADVANCE(32);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (lookahead != 0 &&
          lookahead != ':' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(41);
      END_STATE();
    case 18:
      if (eof) ADVANCE(20);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == '@') ADVANCE(13);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '|') ADVANCE(32);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '@') ADVANCE(13);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '|') ADVANCE(32);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(41);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ':' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(41);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ':' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_alias_name_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_alias_value);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_alias_value);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_alias_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ':' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '(') ADVANCE(41);
      if (lookahead == ')') ADVANCE(34);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ':' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ':' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'l') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(41);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'l') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(41);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'u') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ':' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_null);
      if (lookahead == ':') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_null);
      if (lookahead == ':') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_action_name);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_args);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 18},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 18},
  [8] = {.lex_state = 18},
  [9] = {.lex_state = 18},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 18},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 18},
  [15] = {.lex_state = 19},
  [16] = {.lex_state = 19},
  [17] = {.lex_state = 18},
  [18] = {.lex_state = 17},
  [19] = {.lex_state = 17},
  [20] = {.lex_state = 18},
  [21] = {.lex_state = 18},
  [22] = {.lex_state = 18},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 18},
  [25] = {.lex_state = 18},
  [26] = {.lex_state = 18},
  [27] = {.lex_state = 18},
  [28] = {.lex_state = 18},
  [29] = {.lex_state = 18},
  [30] = {.lex_state = 18},
  [31] = {.lex_state = 18},
  [32] = {.lex_state = 18},
  [33] = {.lex_state = 18},
  [34] = {.lex_state = 18},
  [35] = {.lex_state = 18},
  [36] = {.lex_state = 18},
  [37] = {.lex_state = 18},
  [38] = {.lex_state = 18},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 18},
  [41] = {.lex_state = 18},
  [42] = {.lex_state = 18},
  [43] = {.lex_state = 18},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_action_name] = ACTIONS(1),
    [sym_args] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(46),
    [sym__item] = STATE(5),
    [sym_body_def] = STATE(5),
    [sym_body_use] = STATE(5),
    [sym_alias] = STATE(5),
    [sym_alias_name] = STATE(49),
    [sym_block] = STATE(5),
    [sym_context_header] = STATE(48),
    [sym_alias_ref] = STATE(17),
    [sym_prefix_header] = STATE(48),
    [sym_binding] = STATE(5),
    [sym_keys] = STATE(47),
    [sym_key] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_context_header_repeat1] = STATE(13),
    [aux_sym_prefix_header_repeat1] = STATE(41),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__item] = STATE(11),
    [sym_body_def] = STATE(11),
    [sym_body_use] = STATE(11),
    [sym_alias] = STATE(11),
    [sym_alias_name] = STATE(51),
    [sym_block] = STATE(11),
    [sym_context_header] = STATE(52),
    [sym_alias_ref] = STATE(21),
    [sym_prefix_header] = STATE(52),
    [sym_binding] = STATE(11),
    [sym_keys] = STATE(53),
    [sym_key] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_context_header_repeat1] = STATE(13),
    [aux_sym_prefix_header_repeat1] = STATE(41),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__item] = STATE(11),
    [sym_body_def] = STATE(11),
    [sym_body_use] = STATE(11),
    [sym_alias] = STATE(11),
    [sym_alias_name] = STATE(51),
    [sym_block] = STATE(11),
    [sym_context_header] = STATE(52),
    [sym_alias_ref] = STATE(21),
    [sym_prefix_header] = STATE(52),
    [sym_binding] = STATE(11),
    [sym_keys] = STATE(53),
    [sym_key] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_context_header_repeat1] = STATE(13),
    [aux_sym_prefix_header_repeat1] = STATE(41),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(4)] = {
    [sym__item] = STATE(8),
    [sym_body_def] = STATE(8),
    [sym_body_use] = STATE(8),
    [sym_alias] = STATE(8),
    [sym_alias_name] = STATE(51),
    [sym_block] = STATE(8),
    [sym_context_header] = STATE(52),
    [sym_alias_ref] = STATE(21),
    [sym_prefix_header] = STATE(52),
    [sym_binding] = STATE(8),
    [sym_keys] = STATE(53),
    [sym_key] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_context_header_repeat1] = STATE(13),
    [aux_sym_prefix_header_repeat1] = STATE(41),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(5)] = {
    [sym__item] = STATE(6),
    [sym_body_def] = STATE(6),
    [sym_body_use] = STATE(6),
    [sym_alias] = STATE(6),
    [sym_alias_name] = STATE(49),
    [sym_block] = STATE(6),
    [sym_context_header] = STATE(48),
    [sym_alias_ref] = STATE(17),
    [sym_prefix_header] = STATE(48),
    [sym_binding] = STATE(6),
    [sym_keys] = STATE(47),
    [sym_key] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_context_header_repeat1] = STATE(13),
    [aux_sym_prefix_header_repeat1] = STATE(41),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_ident] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(6)] = {
    [sym__item] = STATE(6),
    [sym_body_def] = STATE(6),
    [sym_body_use] = STATE(6),
    [sym_alias] = STATE(6),
    [sym_alias_name] = STATE(49),
    [sym_block] = STATE(6),
    [sym_context_header] = STATE(48),
    [sym_alias_ref] = STATE(17),
    [sym_prefix_header] = STATE(48),
    [sym_binding] = STATE(6),
    [sym_keys] = STATE(47),
    [sym_key] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_context_header_repeat1] = STATE(13),
    [aux_sym_prefix_header_repeat1] = STATE(41),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_ident] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(30),
    [anon_sym_PIPE] = ACTIONS(33),
    [sym_string] = ACTIONS(36),
  },
  [STATE(7)] = {
    [sym__item] = STATE(2),
    [sym_body_def] = STATE(2),
    [sym_body_use] = STATE(2),
    [sym_alias] = STATE(2),
    [sym_alias_name] = STATE(51),
    [sym_block] = STATE(2),
    [sym_context_header] = STATE(52),
    [sym_alias_ref] = STATE(21),
    [sym_prefix_header] = STATE(52),
    [sym_binding] = STATE(2),
    [sym_keys] = STATE(53),
    [sym_key] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_context_header_repeat1] = STATE(13),
    [aux_sym_prefix_header_repeat1] = STATE(41),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(8)] = {
    [sym__item] = STATE(11),
    [sym_body_def] = STATE(11),
    [sym_body_use] = STATE(11),
    [sym_alias] = STATE(11),
    [sym_alias_name] = STATE(51),
    [sym_block] = STATE(11),
    [sym_context_header] = STATE(52),
    [sym_alias_ref] = STATE(21),
    [sym_prefix_header] = STATE(52),
    [sym_binding] = STATE(11),
    [sym_keys] = STATE(53),
    [sym_key] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_context_header_repeat1] = STATE(13),
    [aux_sym_prefix_header_repeat1] = STATE(41),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(41),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(9)] = {
    [sym__item] = STATE(12),
    [sym_body_def] = STATE(12),
    [sym_body_use] = STATE(12),
    [sym_alias] = STATE(12),
    [sym_alias_name] = STATE(51),
    [sym_block] = STATE(12),
    [sym_context_header] = STATE(52),
    [sym_alias_ref] = STATE(21),
    [sym_prefix_header] = STATE(52),
    [sym_binding] = STATE(12),
    [sym_keys] = STATE(53),
    [sym_key] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_context_header_repeat1] = STATE(13),
    [aux_sym_prefix_header_repeat1] = STATE(41),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(43),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(10)] = {
    [sym__item] = STATE(3),
    [sym_body_def] = STATE(3),
    [sym_body_use] = STATE(3),
    [sym_alias] = STATE(3),
    [sym_alias_name] = STATE(51),
    [sym_block] = STATE(3),
    [sym_context_header] = STATE(52),
    [sym_alias_ref] = STATE(21),
    [sym_prefix_header] = STATE(52),
    [sym_binding] = STATE(3),
    [sym_keys] = STATE(53),
    [sym_key] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_context_header_repeat1] = STATE(13),
    [aux_sym_prefix_header_repeat1] = STATE(41),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(45),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
  [STATE(11)] = {
    [sym__item] = STATE(11),
    [sym_body_def] = STATE(11),
    [sym_body_use] = STATE(11),
    [sym_alias] = STATE(11),
    [sym_alias_name] = STATE(51),
    [sym_block] = STATE(11),
    [sym_context_header] = STATE(52),
    [sym_alias_ref] = STATE(21),
    [sym_prefix_header] = STATE(52),
    [sym_binding] = STATE(11),
    [sym_keys] = STATE(53),
    [sym_key] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_context_header_repeat1] = STATE(13),
    [aux_sym_prefix_header_repeat1] = STATE(41),
    [sym_ident] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(47),
    [anon_sym_PIPE] = ACTIONS(33),
    [sym_string] = ACTIONS(36),
  },
  [STATE(12)] = {
    [sym__item] = STATE(11),
    [sym_body_def] = STATE(11),
    [sym_body_use] = STATE(11),
    [sym_alias] = STATE(11),
    [sym_alias_name] = STATE(51),
    [sym_block] = STATE(11),
    [sym_context_header] = STATE(52),
    [sym_alias_ref] = STATE(21),
    [sym_prefix_header] = STATE(52),
    [sym_binding] = STATE(11),
    [sym_keys] = STATE(53),
    [sym_key] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_context_header_repeat1] = STATE(13),
    [aux_sym_prefix_header_repeat1] = STATE(41),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(50),
    [sym_comment] = ACTIONS(3),
    [aux_sym_alias_name_token1] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      sym_ident,
    ACTIONS(54), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      aux_sym_alias_name_token1,
    ACTIONS(58), 2,
      anon_sym_PIPE,
      sym_string,
    STATE(14), 2,
      sym_alias_ref,
      aux_sym_context_header_repeat1,
  [21] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      aux_sym_alias_name_token1,
    ACTIONS(68), 2,
      anon_sym_PIPE,
      sym_string,
    STATE(14), 2,
      sym_alias_ref,
      aux_sym_context_header_repeat1,
  [42] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_ident,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(71), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [59] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_ident,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(71), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [76] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      sym_ident,
    ACTIONS(82), 1,
      anon_sym_LBRACE,
    ACTIONS(84), 3,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [94] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_ident,
    ACTIONS(91), 1,
      sym_args,
    ACTIONS(87), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [110] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_ident,
    ACTIONS(93), 1,
      sym_args,
    ACTIONS(87), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [126] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_ident,
    ACTIONS(98), 1,
      anon_sym_COLON,
    ACTIONS(100), 1,
      sym_string,
    ACTIONS(82), 3,
      anon_sym_LBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
  [144] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    ACTIONS(79), 1,
      sym_ident,
    ACTIONS(82), 1,
      anon_sym_LBRACE,
    ACTIONS(84), 3,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [162] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      sym_ident,
    ACTIONS(103), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [175] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      sym_null,
    ACTIONS(109), 1,
      sym_action_name,
    STATE(26), 1,
      sym_actions,
    STATE(22), 2,
      sym__action,
      sym_action,
  [192] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_ident,
    ACTIONS(71), 4,
      anon_sym_LBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [205] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym_ident,
    ACTIONS(111), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [218] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_ident,
    ACTIONS(115), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [231] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_ident,
    ACTIONS(119), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [244] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_ident,
    ACTIONS(123), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [257] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_ident,
    ACTIONS(127), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [270] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [283] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_ident,
    ACTIONS(137), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [296] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_ident,
    ACTIONS(137), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [309] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_ident,
    ACTIONS(115), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [322] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      sym_ident,
    ACTIONS(103), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [335] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_ident,
    ACTIONS(123), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [348] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_ident,
    ACTIONS(127), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [361] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_ident,
    ACTIONS(119), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [374] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym_ident,
    ACTIONS(111), 4,
      anon_sym_RBRACE,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [387] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_null,
    ACTIONS(141), 1,
      sym_action_name,
    STATE(33), 1,
      sym_actions,
    STATE(34), 2,
      sym__action,
      sym_action,
  [404] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_ident,
    ACTIONS(146), 1,
      anon_sym_COLON,
    ACTIONS(148), 1,
      sym_string,
    STATE(40), 2,
      sym_key,
      aux_sym_prefix_header_repeat1,
  [421] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      sym_ident,
    ACTIONS(153), 1,
      anon_sym_COLON,
    ACTIONS(156), 1,
      sym_string,
    STATE(40), 2,
      sym_key,
      aux_sym_prefix_header_repeat1,
  [438] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 4,
      ts_builtin_sym_end,
      aux_sym_alias_name_token1,
      anon_sym_PIPE,
      sym_string,
  [451] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym_ident,
    ACTIONS(98), 2,
      anon_sym_COLON,
      sym_string,
  [462] = 3,
    ACTIONS(160), 1,
      anon_sym_LBRACE,
    ACTIONS(162), 1,
      sym_comment,
    ACTIONS(164), 1,
      sym_alias_value,
  [472] = 3,
    ACTIONS(162), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    ACTIONS(168), 1,
      sym_alias_value,
  [482] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      ts_builtin_sym_end,
  [489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_COLON,
  [496] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
  [503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_EQ,
  [510] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_LBRACE,
  [517] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_EQ,
  [524] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
  [531] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 21,
  [SMALL_STATE(15)] = 42,
  [SMALL_STATE(16)] = 59,
  [SMALL_STATE(17)] = 76,
  [SMALL_STATE(18)] = 94,
  [SMALL_STATE(19)] = 110,
  [SMALL_STATE(20)] = 126,
  [SMALL_STATE(21)] = 144,
  [SMALL_STATE(22)] = 162,
  [SMALL_STATE(23)] = 175,
  [SMALL_STATE(24)] = 192,
  [SMALL_STATE(25)] = 205,
  [SMALL_STATE(26)] = 218,
  [SMALL_STATE(27)] = 231,
  [SMALL_STATE(28)] = 244,
  [SMALL_STATE(29)] = 257,
  [SMALL_STATE(30)] = 270,
  [SMALL_STATE(31)] = 283,
  [SMALL_STATE(32)] = 296,
  [SMALL_STATE(33)] = 309,
  [SMALL_STATE(34)] = 322,
  [SMALL_STATE(35)] = 335,
  [SMALL_STATE(36)] = 348,
  [SMALL_STATE(37)] = 361,
  [SMALL_STATE(38)] = 374,
  [SMALL_STATE(39)] = 387,
  [SMALL_STATE(40)] = 404,
  [SMALL_STATE(41)] = 421,
  [SMALL_STATE(42)] = 438,
  [SMALL_STATE(43)] = 451,
  [SMALL_STATE(44)] = 462,
  [SMALL_STATE(45)] = 472,
  [SMALL_STATE(46)] = 482,
  [SMALL_STATE(47)] = 489,
  [SMALL_STATE(48)] = 496,
  [SMALL_STATE(49)] = 503,
  [SMALL_STATE(50)] = 510,
  [SMALL_STATE(51)] = 517,
  [SMALL_STATE(52)] = 524,
  [SMALL_STATE(53)] = 531,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context_header, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_ref, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_ref, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_name, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_use, 1, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_body_use, 1, 0, 0), REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_body_use, 1, 0, 0), REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 1, 0, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 1, 0, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_key, 1, 0, 0), REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_key, 1, 0, 0), REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_actions, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_actions, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_def, 5, 0, 3),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_def, 5, 0, 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 3, 0, 4),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding, 3, 0, 4),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 2, 0, 5),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 2, 0, 5),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_def, 4, 0, 3),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_def, 4, 0, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 2),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 2),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias, 3, 0, 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 3, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 2),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prefix_header_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_prefix_header_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prefix_header_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_keys, 1, 0, 0), SHIFT(50),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [170] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_header, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_keycook(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
    .name = "keycook",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
