/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 32
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_ident = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  sym_comment = 4,
  sym_alias_name = 5,
  sym_alias_value = 6,
  anon_sym_AMP_AMP = 7,
  anon_sym_PIPE_PIPE = 8,
  anon_sym_AMP = 9,
  anon_sym_PIPE = 10,
  anon_sym_BANG_EQ = 11,
  anon_sym_EQ_EQ = 12,
  anon_sym_EQ = 13,
  anon_sym_BANG = 14,
  anon_sym_GT = 15,
  anon_sym_LT = 16,
  anon_sym_LPAREN = 17,
  anon_sym_RPAREN = 18,
  sym_alias_ref = 19,
  anon_sym_COLON = 20,
  sym_null = 21,
  sym_action_name = 22,
  sym_args = 23,
  sym_string = 24,
  sym_source_file = 25,
  sym__item = 26,
  sym_body_def = 27,
  sym_body_use = 28,
  sym_alias = 29,
  sym_block = 30,
  sym_context_header = 31,
  sym_operator = 32,
  sym_paren = 33,
  sym_prefix_header = 34,
  sym_binding = 35,
  sym_keys = 36,
  sym_key = 37,
  sym_actions = 38,
  sym__action = 39,
  sym_action = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_context_header_repeat1 = 42,
  aux_sym_prefix_header_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_comment] = "comment",
  [sym_alias_name] = "alias_name",
  [sym_alias_value] = "alias_value",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP] = "&",
  [anon_sym_PIPE] = "|",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG] = "!",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_alias_ref] = "alias_ref",
  [anon_sym_COLON] = ":",
  [sym_null] = "null",
  [sym_action_name] = "action_name",
  [sym_args] = "args",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_body_def] = "body_def",
  [sym_body_use] = "body_use",
  [sym_alias] = "alias",
  [sym_block] = "block",
  [sym_context_header] = "context_header",
  [sym_operator] = "operator",
  [sym_paren] = "paren",
  [sym_prefix_header] = "prefix_header",
  [sym_binding] = "binding",
  [sym_keys] = "keys",
  [sym_key] = "key",
  [sym_actions] = "actions",
  [sym__action] = "_action",
  [sym_action] = "action",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_context_header_repeat1] = "context_header_repeat1",
  [aux_sym_prefix_header_repeat1] = "prefix_header_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_comment] = sym_comment,
  [sym_alias_name] = sym_alias_name,
  [sym_alias_value] = sym_alias_value,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_alias_ref] = sym_alias_ref,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_null] = sym_null,
  [sym_action_name] = sym_action_name,
  [sym_args] = sym_args,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_body_def] = sym_body_def,
  [sym_body_use] = sym_body_use,
  [sym_alias] = sym_alias,
  [sym_block] = sym_block,
  [sym_context_header] = sym_context_header,
  [sym_operator] = sym_operator,
  [sym_paren] = sym_paren,
  [sym_prefix_header] = sym_prefix_header,
  [sym_binding] = sym_binding,
  [sym_keys] = sym_keys,
  [sym_key] = sym_key,
  [sym_actions] = sym_actions,
  [sym__action] = sym__action,
  [sym_action] = sym_action,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_context_header_repeat1] = aux_sym_context_header_repeat1,
  [aux_sym_prefix_header_repeat1] = aux_sym_prefix_header_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_name] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_alias_ref] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_action_name] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_body_def] = {
    .visible = true,
    .named = true,
  },
  [sym_body_use] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_context_header] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_header] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_keys] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_actions] = {
    .visible = true,
    .named = true,
  },
  [sym__action] = {
    .visible = false,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_context_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_prefix_header_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_actions = 1,
  field_args = 2,
  field_header = 3,
  field_keys = 4,
  field_name = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_actions] = "actions",
  [field_args] = "args",
  [field_header] = "header",
  [field_keys] = "keys",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 1},
  [2] =
    {field_name, 0},
  [3] =
    {field_header, 0},
  [4] =
    {field_actions, 2},
    {field_keys, 0},
  [6] =
    {field_args, 1},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
};

static const TSCharacterRange sym_ident_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'#', '%'}, {'\'', '\''}, {'*', '9'}, {';', ';'}, {'?', '?'}, {'A', 'z'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '!', 39,
        '"', 3,
        '&', 34,
        '(', 43,
        ')', 44,
        '/', 48,
        ':', 47,
        '<', 41,
        '=', 38,
        '>', 40,
        '@', 15,
        'n', 51,
        '{', 23,
        '|', 35,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == '{') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 39,
        '"', 3,
        '&', 34,
        '(', 42,
        ')', 44,
        '/', 48,
        ':', 47,
        '<', 41,
        '=', 38,
        '>', 40,
        '@', 16,
        '{', 23,
        '|', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(53);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == ')') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == 'n') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'l') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'l') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'u') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 15:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 16:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 17:
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 20:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '!', 39,
        '"', 3,
        '&', 34,
        '(', 43,
        ')', 44,
        '/', 48,
        '<', 41,
        '=', 38,
        '>', 40,
        '@', 15,
        '|', 35,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (lookahead != 0 &&
          lookahead != ':' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(53);
      END_STATE();
    case 21:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '!', 39,
        '"', 3,
        '&', 34,
        '(', 42,
        ')', 44,
        '/', 48,
        ':', 47,
        '<', 41,
        '=', 38,
        '>', 40,
        '@', 15,
        '{', 23,
        '|', 35,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          (' ' <= lookahead && lookahead <= '"') ||
          lookahead == '&' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '>') ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_alias_name);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_alias_value);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_alias_value);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_alias_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(32);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(33);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(36);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_alias_ref);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_alias_ref);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '/') ADVANCE(26);
      if ((!eof && set_contains(sym_ident_character_set_1, 9, lookahead)) ||
          lookahead == '@') ADVANCE(53);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'l') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '"' < lookahead) &&
          lookahead != '&' &&
          lookahead != '(' &&
          lookahead != ')' &&
          (lookahead < '<' || '>' < lookahead) &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'l') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '"' < lookahead) &&
          lookahead != '&' &&
          lookahead != '(' &&
          lookahead != ')' &&
          (lookahead < '<' || '>' < lookahead) &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(53);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'u') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '"' < lookahead) &&
          lookahead != '&' &&
          lookahead != '(' &&
          lookahead != ')' &&
          (lookahead < '<' || '>' < lookahead) &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == ':') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '"' < lookahead) &&
          lookahead != '&' &&
          lookahead != '(' &&
          lookahead != ')' &&
          (lookahead < '<' || '>' < lookahead) &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_ident);
      if ((!eof && set_contains(sym_ident_character_set_1, 9, lookahead)) ||
          lookahead == '@') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_null);
      if (lookahead == ':') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '"' < lookahead) &&
          lookahead != '&' &&
          lookahead != '(' &&
          lookahead != ')' &&
          (lookahead < '<' || '>' < lookahead) &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_null);
      if (lookahead == ':') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_action_name);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_args);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 21},
  [2] = {.lex_state = 21},
  [3] = {.lex_state = 21},
  [4] = {.lex_state = 21},
  [5] = {.lex_state = 21},
  [6] = {.lex_state = 21},
  [7] = {.lex_state = 21},
  [8] = {.lex_state = 21},
  [9] = {.lex_state = 21},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 21},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 20},
  [14] = {.lex_state = 21},
  [15] = {.lex_state = 21},
  [16] = {.lex_state = 21},
  [17] = {.lex_state = 21},
  [18] = {.lex_state = 21},
  [19] = {.lex_state = 21},
  [20] = {.lex_state = 21},
  [21] = {.lex_state = 21},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 21},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_alias_name] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_alias_ref] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_action_name] = ACTIONS(1),
    [sym_args] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(29),
    [sym__item] = STATE(3),
    [sym_body_def] = STATE(3),
    [sym_body_use] = STATE(3),
    [sym_alias] = STATE(3),
    [sym_block] = STATE(3),
    [sym_context_header] = STATE(30),
    [sym_operator] = STATE(24),
    [sym_paren] = STATE(24),
    [sym_prefix_header] = STATE(30),
    [sym_binding] = STATE(3),
    [sym_keys] = STATE(28),
    [sym_key] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_context_header_repeat1] = STATE(10),
    [aux_sym_prefix_header_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym_alias_name] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(11),
    [anon_sym_PIPE_PIPE] = ACTIONS(11),
    [anon_sym_AMP] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
    [sym_alias_ref] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym__item] = STATE(2),
    [sym_body_def] = STATE(2),
    [sym_body_use] = STATE(2),
    [sym_alias] = STATE(2),
    [sym_block] = STATE(2),
    [sym_context_header] = STATE(30),
    [sym_operator] = STATE(24),
    [sym_paren] = STATE(24),
    [sym_prefix_header] = STATE(30),
    [sym_binding] = STATE(2),
    [sym_keys] = STATE(28),
    [sym_key] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_context_header_repeat1] = STATE(10),
    [aux_sym_prefix_header_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_ident] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [sym_alias_name] = ACTIONS(26),
    [anon_sym_AMP_AMP] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_AMP] = ACTIONS(32),
    [anon_sym_PIPE] = ACTIONS(32),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_EQ_EQ] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(32),
    [anon_sym_BANG] = ACTIONS(32),
    [anon_sym_GT] = ACTIONS(29),
    [anon_sym_LT] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(35),
    [sym_alias_ref] = ACTIONS(38),
    [sym_string] = ACTIONS(41),
  },
  [STATE(3)] = {
    [sym__item] = STATE(2),
    [sym_body_def] = STATE(2),
    [sym_body_use] = STATE(2),
    [sym_alias] = STATE(2),
    [sym_block] = STATE(2),
    [sym_context_header] = STATE(30),
    [sym_operator] = STATE(24),
    [sym_paren] = STATE(24),
    [sym_prefix_header] = STATE(30),
    [sym_binding] = STATE(2),
    [sym_keys] = STATE(28),
    [sym_key] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_context_header_repeat1] = STATE(10),
    [aux_sym_prefix_header_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(44),
    [sym_ident] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym_alias_name] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(11),
    [anon_sym_PIPE_PIPE] = ACTIONS(11),
    [anon_sym_AMP] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
    [sym_alias_ref] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym__item] = STATE(6),
    [sym_body_def] = STATE(6),
    [sym_body_use] = STATE(6),
    [sym_alias] = STATE(6),
    [sym_block] = STATE(6),
    [sym_context_header] = STATE(30),
    [sym_operator] = STATE(24),
    [sym_paren] = STATE(24),
    [sym_prefix_header] = STATE(30),
    [sym_binding] = STATE(6),
    [sym_keys] = STATE(28),
    [sym_key] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_context_header_repeat1] = STATE(10),
    [aux_sym_prefix_header_repeat1] = STATE(8),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(46),
    [sym_comment] = ACTIONS(3),
    [sym_alias_name] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(11),
    [anon_sym_PIPE_PIPE] = ACTIONS(11),
    [anon_sym_AMP] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
    [sym_alias_ref] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
  },
  [STATE(5)] = {
    [sym__item] = STATE(7),
    [sym_body_def] = STATE(7),
    [sym_body_use] = STATE(7),
    [sym_alias] = STATE(7),
    [sym_block] = STATE(7),
    [sym_context_header] = STATE(30),
    [sym_operator] = STATE(24),
    [sym_paren] = STATE(24),
    [sym_prefix_header] = STATE(30),
    [sym_binding] = STATE(7),
    [sym_keys] = STATE(28),
    [sym_key] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_context_header_repeat1] = STATE(10),
    [aux_sym_prefix_header_repeat1] = STATE(8),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(48),
    [sym_comment] = ACTIONS(3),
    [sym_alias_name] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(11),
    [anon_sym_PIPE_PIPE] = ACTIONS(11),
    [anon_sym_AMP] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
    [sym_alias_ref] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
  },
  [STATE(6)] = {
    [sym__item] = STATE(2),
    [sym_body_def] = STATE(2),
    [sym_body_use] = STATE(2),
    [sym_alias] = STATE(2),
    [sym_block] = STATE(2),
    [sym_context_header] = STATE(30),
    [sym_operator] = STATE(24),
    [sym_paren] = STATE(24),
    [sym_prefix_header] = STATE(30),
    [sym_binding] = STATE(2),
    [sym_keys] = STATE(28),
    [sym_key] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_context_header_repeat1] = STATE(10),
    [aux_sym_prefix_header_repeat1] = STATE(8),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(50),
    [sym_comment] = ACTIONS(3),
    [sym_alias_name] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(11),
    [anon_sym_PIPE_PIPE] = ACTIONS(11),
    [anon_sym_AMP] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
    [sym_alias_ref] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
  },
  [STATE(7)] = {
    [sym__item] = STATE(2),
    [sym_body_def] = STATE(2),
    [sym_body_use] = STATE(2),
    [sym_alias] = STATE(2),
    [sym_block] = STATE(2),
    [sym_context_header] = STATE(30),
    [sym_operator] = STATE(24),
    [sym_paren] = STATE(24),
    [sym_prefix_header] = STATE(30),
    [sym_binding] = STATE(2),
    [sym_keys] = STATE(28),
    [sym_key] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_context_header_repeat1] = STATE(10),
    [aux_sym_prefix_header_repeat1] = STATE(8),
    [sym_ident] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(52),
    [sym_comment] = ACTIONS(3),
    [sym_alias_name] = ACTIONS(9),
    [anon_sym_AMP_AMP] = ACTIONS(11),
    [anon_sym_PIPE_PIPE] = ACTIONS(11),
    [anon_sym_AMP] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
    [sym_alias_ref] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      sym_ident,
    ACTIONS(56), 1,
      anon_sym_COLON,
    ACTIONS(59), 1,
      sym_string,
    ACTIONS(15), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    STATE(11), 2,
      sym_key,
      aux_sym_prefix_header_repeat1,
    STATE(25), 2,
      sym_operator,
      sym_paren,
    ACTIONS(13), 4,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
    ACTIONS(11), 6,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
  [39] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_alias_name,
    ACTIONS(63), 6,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_alias_ref,
      sym_ident,
    ACTIONS(68), 9,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
  [70] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      sym_ident,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(75), 2,
      sym_alias_ref,
      sym_string,
    STATE(12), 3,
      sym_operator,
      sym_paren,
      aux_sym_context_header_repeat1,
    ACTIONS(13), 4,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
    ACTIONS(11), 6,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
  [107] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_ident,
    ACTIONS(89), 1,
      anon_sym_COLON,
    ACTIONS(91), 1,
      sym_string,
    ACTIONS(86), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    STATE(11), 2,
      sym_key,
      aux_sym_prefix_header_repeat1,
    STATE(25), 2,
      sym_operator,
      sym_paren,
    ACTIONS(83), 4,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
    ACTIONS(80), 6,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
  [146] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      sym_ident,
    ACTIONS(97), 1,
      anon_sym_LBRACE,
    ACTIONS(105), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(108), 2,
      sym_alias_ref,
      sym_string,
    STATE(12), 3,
      sym_operator,
      sym_paren,
      aux_sym_context_header_repeat1,
    ACTIONS(102), 4,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
    ACTIONS(99), 6,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
  [183] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_args,
    ACTIONS(113), 7,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      anon_sym_LPAREN,
      sym_alias_ref,
      sym_ident,
    ACTIONS(111), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_alias_name,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_RPAREN,
      sym_string,
  [212] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 6,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_alias_ref,
      sym_ident,
    ACTIONS(117), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_alias_name,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
  [238] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 6,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_alias_ref,
      sym_ident,
    ACTIONS(121), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_alias_name,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
  [264] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 6,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_alias_ref,
      sym_ident,
    ACTIONS(125), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_alias_name,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
  [290] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 6,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_alias_ref,
      sym_ident,
    ACTIONS(129), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_alias_name,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
  [316] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 6,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_alias_ref,
      sym_ident,
    ACTIONS(133), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_alias_name,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
  [342] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 6,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_alias_ref,
      sym_ident,
    ACTIONS(137), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_alias_name,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
  [368] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 6,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_alias_ref,
      sym_ident,
    ACTIONS(141), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_alias_name,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
  [394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 6,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_alias_ref,
      sym_ident,
    ACTIONS(145), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_alias_name,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
  [420] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 5,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_ident,
    ACTIONS(151), 12,
      anon_sym_LBRACE,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_alias_ref,
      anon_sym_COLON,
      sym_string,
  [445] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 5,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_ident,
    ACTIONS(155), 12,
      anon_sym_LBRACE,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_alias_ref,
      anon_sym_COLON,
      sym_string,
  [470] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_COLON,
    ACTIONS(66), 2,
      anon_sym_LBRACE,
      sym_alias_ref,
    ACTIONS(157), 5,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_ident,
    ACTIONS(160), 9,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
  [499] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 5,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_EQ,
      anon_sym_BANG,
      sym_ident,
    ACTIONS(163), 10,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      sym_string,
  [522] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_null,
    ACTIONS(169), 1,
      sym_action_name,
    STATE(17), 1,
      sym_actions,
    STATE(16), 2,
      sym__action,
      sym_action,
  [539] = 3,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    ACTIONS(173), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym_alias_value,
  [549] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_COLON,
  [556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
  [563] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
  [570] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 39,
  [SMALL_STATE(10)] = 70,
  [SMALL_STATE(11)] = 107,
  [SMALL_STATE(12)] = 146,
  [SMALL_STATE(13)] = 183,
  [SMALL_STATE(14)] = 212,
  [SMALL_STATE(15)] = 238,
  [SMALL_STATE(16)] = 264,
  [SMALL_STATE(17)] = 290,
  [SMALL_STATE(18)] = 316,
  [SMALL_STATE(19)] = 342,
  [SMALL_STATE(20)] = 368,
  [SMALL_STATE(21)] = 394,
  [SMALL_STATE(22)] = 420,
  [SMALL_STATE(23)] = 445,
  [SMALL_STATE(24)] = 470,
  [SMALL_STATE(25)] = 499,
  [SMALL_STATE(26)] = 522,
  [SMALL_STATE(27)] = 539,
  [SMALL_STATE(28)] = 549,
  [SMALL_STATE(29)] = 556,
  [SMALL_STATE(30)] = 563,
  [SMALL_STATE(31)] = 570,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_keys, 1, 0, 0), SHIFT(31),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_use, 1, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_body_use, 1, 0, 0), REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_body_use, 1, 0, 0), REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context_header, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prefix_header_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prefix_header_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prefix_header_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prefix_header_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_prefix_header_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prefix_header_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_header_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 1, 0, 2),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 1, 0, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 2, 0, 1),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias, 2, 0, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_def, 3, 0, 2),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_def, 3, 0, 2),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_actions, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_actions, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 3, 0, 4),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding, 3, 0, 4),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_def, 4, 0, 2),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_def, 4, 0, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 3),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 2, 0, 5),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 2, 0, 5),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [157] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_key, 1, 0, 0), REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_key, 1, 0, 0), REDUCE(aux_sym_context_header_repeat1, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [179] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_header, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_keycook(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
    .name = "keycook",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
