//! Render sections as Zed's keymap.json (JSON with comments, which Zed accepts).

use crate::compile::Section;

pub fn render(sections: &[Section], source_name: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("// GENERATED by keycook from {source_name} — edit the .kc file, not this one.\n"));
    out.push_str("// Nesting in the source became `&&` here; `>` headers became Zed's descendant operator.\n[\n");
    for s in sections {
        if s.bindings.is_empty() {
            continue;
        }
        out.push_str(&format!("  // {}\n  {{\n", s.path));
        if !s.context.is_empty() {
            out.push_str(&format!("    \"context\": {},\n", serde_json::to_string(&s.context).unwrap()));
        }
        out.push_str("    \"bindings\": {\n");
        for b in &s.bindings {
            out.push_str(&format!("      {}: {},\n", serde_json::to_string(&b.key).unwrap(), serde_json::to_string(&b.value).unwrap()));
        }
        out.push_str("    },\n  },\n");
    }
    out.push_str("]\n");
    out
}
